name: Analysis (macOS)

on:
  workflow_dispatch:

jobs:
  encode:
    runs-on: macos-latest
    timeout-minutes: 360  # 6 hour timeout
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up workspace
        run: |
          mkdir -p encoded_videos
          
      - name: Save macOS script from secret
        run: |
          cat > macos.sh << 'SCRIPT_EOF'
          ${{ secrets.MACOS_ENCODER_SCRIPT }}
          SCRIPT_EOF
          chmod +x macos.sh
        
      - name: Run encoder script on macOS
        run: |
          bash macos.sh
        
      - name: Clean up workspace
        if: always()
        run: |
          rm -f macos.sh
          rm -rf encoded_videos/
