name: H.265 Video Encoder-4-core

on:
  workflow_dispatch:

jobs:
  encode:
    runs-on: ubuntu-latest-4-core
    timeout-minutes: 360  # 6 hour timeout
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up workspace
        run: |
          mkdir -p encoded_videos
          
      - name: Save script from secret (safer method)
        run: |
          cat > encoder.sh << 'SCRIPT_EOF'
          ${{ secrets.ENCODER_SCRIPT }}
          SCRIPT_EOF
          chmod +x encoder.sh
        
      - name: Run encoder script with sudo
        run: |
          sudo bash encoder.sh
        
      - name: Clean up workspace
        if: always()
        run: |
          rm -f encoder.sh
          rm -rf encoded_videos/
