name: Audio Transcription (macOS)

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'Whisper model to use'
        required: true
        default: 'large-v3'
        type: choice
        options:
          - tiny
          - tiny.en
          - base
          - base.en
          - small
          - small.en
          - medium
          - medium.en
          - large-v1
          - large-v2
          - large-v3
          - large-v3-turbo
      language:
        description: 'Language code (auto for auto-detection)'
        required: false
        default: 'auto'
        type: string
      test_mode:
        description: 'Enable test mode (process only first 60 seconds)'
        required: false
        default: false
        type: boolean
  schedule:
    # Run every 4 hours to check for new audio files
    - cron: '0 */4 * * *'

jobs:
  transcribe:
    runs-on: macos-latest
    timeout-minutes: 360  # 6 hour timeout
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up workspace
      run: |
        mkdir -p transcriptions
        
    - name: Save macOS whisper script from secret
      run: |
        cat > whisper-macos.sh << 'SCRIPT_EOF'
        ${{ secrets.WHISPER_MACOS_SCRIPT }}
        SCRIPT_EOF
        chmod +x whisper-macos.sh
        
    - name: Configure script with workflow inputs
      run: |
        # Set up environment variables and update script configuration
        WHISPER_MODEL="${{ github.event.inputs.model || 'large-v3' }}"
        LANGUAGE="${{ github.event.inputs.language || 'auto' }}"
        TEST_MODE="${{ github.event.inputs.test_mode == 'true' && '1' || '0' }}"
        
        # Update the script with workflow inputs
        sed -i '' "s/WHISPER_MODEL=\"large-v3\"/WHISPER_MODEL=\"$WHISPER_MODEL\"/" whisper-macos.sh
        sed -i '' "s/LANGUAGE=\"auto\"/LANGUAGE=\"$LANGUAGE\"/" whisper-macos.sh
        sed -i '' "s/TEST_MODE=0/TEST_MODE=$TEST_MODE/" whisper-macos.sh
        
        echo "=== Configuration ==="
        echo "Model: $WHISPER_MODEL"
        echo "Language: $LANGUAGE"
        echo "Test Mode: $TEST_MODE"
        echo "===================="
        
    - name: Run whisper transcription script on macOS
      run: |
        bash whisper-macos.sh        
    - name: Clean up workspace
      if: always()
      run: |
        rm -f whisper-macos.sh
        rm -rf transcriptions/
        rm -rf whisper.cpp/
        rm -rf *.wav *.mp3 *.m4a *.mp4 *.mkv
        echo "Cleaned up temporary files after failure"
